#ifndef TM4C_DEEPDIVE_GPIO_H
#define TM4C_DEEPDIVE_GPIO_H

#include "hwreg.h"

#define GPIOA_BASE_AHB 0x40058000
#define GPIOB_BASE_APB 0x40005000
#define GPIOB_BASE_AHB 0x40059000
#define GPIOC_BASE_APB 0x40006000
#define GPIOC_BASE_AHB 0x4005A000
#define GPIOD_BASE_APB 0x40007000
#define GPIOD_BASE_AHB 0x4005B000
#define GPIOE_BASE_APB 0x40024000
#define GPIOE_BASE_AHB 0x4005C000
#define GPIOF_BASE_APB 0x40025000
#define GPIOF_BASE_AHB 0x4005D000

#define GPIOFDATA_APB(n) HWREG32(GPIOF_BASE_APB + (((n) & 0xff) << 2))
#define GPIOFDIR_APB HWREG32(GPIOF_BASE_APB + 0x400)
#define GPIOFAFSEL_APB HWREG32(GPIOF_BASE_APB + 0x420)
#define GPIOFPUR_APB HWREG32(GPIOF_BASE_APB +  0x510)
#define GPIOFPDR_APB HWREG32(GPIOF_BASE_APB +  0x514)
#define GPIOFDEN_APB HWREG32(GPIOF_BASE_APB + 0x51c)
#define GPIOFPCTL_APB HWREG32(GPIOF_BASE_APB + 0x52c)

#define GPIO_PNAME(name, bus) name##_##bus

#ifdef USE_AHB
// TODO
#else
// APB not available for GPIO A
#define GPIOB_BASE GPIO_PNAME(GPIOB_BASE, APB)
#define GPIOC_BASE GPIO_PNAME(GPIOC_BASE, APB)
#define GPIOD_BASE GPIO_PNAME(GPIOD_BASE, APB)
#define GPIOE_BASE GPIO_PNAME(GPIOE_BASE, APB)
#define GPIOF_BASE GPIO_PNAME(GPIOF_BASE, APB)
#define GPIOFDATA GPIO_PNAME(GPIOFDATA, APB)
#define GPIOFDIR GPIO_PNAME(GPIOFDIR, APB)
#define GPIOFAFSEL GPIO_PNAME(GPIOFAFSEL, APB)
#define GPIOFPUR GPIO_PNAME(GPIOFPUR, APB)
#define GPIOFPDR GPIO_PNAME(GPIOFPDR, APB)
#define GPIOFDEN GPIO_PNAME(GPIOFDEN, APB)
#define GPIOFPCTL GPIO_PNAME(GPIOFPCTL, APB)
#endif

#endif
